version: '2'
services:
  db:
    image: mongo:4.4.6
  web:
    image: goasync:latest
    ports:
    - "1323:1323"
    depends_on:
      - db
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=async
      - MONGODB_COLLECTION=tasks